version: '3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP

services:
  ftpd_server:
#    build:
#      context: .
#      args:
#        network: host
    image: mormond/pure-ftpd:1.0
    container_name: pure-ftpd
    network_mode: "host"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/home/pi/docker/ftp/ftp/ftpusers:/home/"
      - "/home/pi/docker/ftp/ftp/passwd:/etc/pure-ftpd/passwd/"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST:
      FTP_USER_NAME:
      FTP_USER_PASS:
      FTP_USER_HOME:
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: unless-stopped
